# data.py

# 15 Questions per subject
quizzes = {
    "aiml": [
        {"q": "Who is known as the father of AI?", "options": ["Alan Turing", "John McCarthy", "Elon Musk", "Charles Babbage"], "answer": "John McCarthy"},
        {"q": "Which algorithm is used for classification?", "options": ["K-Means", "KNN", "Apriori", "K-Medoids"], "answer": "KNN"},
        {"q": "What does NLP stand for?", "options": ["Neural Language Processing", "Natural Language Processing", "New Language Protocol", "Natural Learning Process"], "answer": "Natural Language Processing"},
        {"q": "Which is a type of Unsupervised Learning?", "options": ["Regression", "Clustering", "Classification", "Decision Trees"], "answer": "Clustering"},
        {"q": "What is the full form of ANN?", "options": ["Artificial Neural Network", "Active Neural Network", "Automated Neural Network", "Advanced Neural Network"], "answer": "Artificial Neural Network"},
        {"q": "In ML, what is 'Overfitting'?", "options": ["Model performs poorly on training data", "Model performs well on training data but poor on new data", "Model is too simple", "Model ignores noise"], "answer": "Model performs well on training data but poor on new data"},
        {"q": "Which library is used for Deep Learning?", "options": ["NumPy", "Pandas", "TensorFlow", "Matplotlib"], "answer": "TensorFlow"},
        {"q": "What is a 'neuron' in a neural network?", "options": ["A database entry", "A mathematical function", "A hardware chip", "A python class"], "answer": "A mathematical function"},
        {"q": "Which search algorithm uses a heuristic?", "options": ["DFS", "BFS", "A*", "Dijkstra"], "answer": "A*"},
        {"q": "What is the Turing Test used for?", "options": ["Testing CPU speed", "Determining if a machine is intelligent", "Testing network speed", "Debugging code"], "answer": "Determining if a machine is intelligent"},
        {"q": "Which is NOT an application of AI?", "options": ["Face Recognition", "Chatbots", "Calculator", "Self-driving cars"], "answer": "Calculator"},
        {"q": "What is Reinforcement Learning?", "options": ["Learning from labeled data", "Learning from feedback/rewards", "Learning without data", "Static programming"], "answer": "Learning from feedback/rewards"},
        {"q": "The number of input layers in a neural network is:", "options": ["Zero", "One", "Multiple", "Infinite"], "answer": "One"},
        {"q": "SVM stands for?", "options": ["Support Vector Machine", "Simple Vector Machine", "Standard Visual Model", "System Vector Method"], "answer": "Support Vector Machine"},
        {"q": "Which activation function is commonly used in output layers for probability?", "options": ["ReLU", "Sigmoid", "Tanh", "Linear"], "answer": "Sigmoid"}
    ],
    "arch": [
        {"q": "What does CPU stand for?", "options": ["Central Process Unit", "Central Processing Unit", "Computer Personal Unit", "Central Processor Usage"], "answer": "Central Processing Unit"},
        {"q": "Which memory is fastest?", "options": ["Hard Disk", "RAM", "Cache", "USB"], "answer": "Cache"},
        {"q": "What is the function of the ALU?", "options": ["Store data", "Perform arithmetic/logic operations", "Control input/output", "Fetch instructions"], "answer": "Perform arithmetic/logic operations"},
        {"q": "RISC stands for?", "options": ["Reduced Instruction Set Computer", "Rapid Instruction Set Computer", "Random Instruction Set Computer", "Real Instruction Source Code"], "answer": "Reduced Instruction Set Computer"},
        {"q": "Which component controls the sequence of operations?", "options": ["ALU", "Control Unit", "Register", "Bus"], "answer": "Control Unit"},
        {"q": "What is a Bus in computer architecture?", "options": ["A vehicle", "A communication system for transferring data", "A type of memory", "A cooling fan"], "answer": "A communication system for transferring data"},
        {"q": "Which of these is non-volatile memory?", "options": ["RAM", "ROM", "Cache", "Register"], "answer": "ROM"},
        {"q": "What is Pipelining?", "options": ["Cooling the CPU", "Executing multiple instructions simultaneously", "Connecting cables", "Cleaning memory"], "answer": "Executing multiple instructions simultaneously"},
        {"q": "The Von Neumann architecture is based on:", "options": ["Stored-program concept", "Neural networks", "Quantum mechanics", "Cloud computing"], "answer": "Stored-program concept"},
        {"q": "What does DMA stand for?", "options": ["Direct Memory Access", "Dual Memory Allocation", "Direct Main Access", "Dynamic Memory Area"], "answer": "Direct Memory Access"},
        {"q": "Which register holds the address of the next instruction?", "options": ["IR", "PC (Program Counter)", "ACC", "MDR"], "answer": "PC (Program Counter)"},
        {"q": "What is the size of a nibble?", "options": ["4 bits", "8 bits", "16 bits", "32 bits"], "answer": "4 bits"},
        {"q": "CISC stands for?", "options": ["Complex Instruction Set Computer", "Common Instruction Set Computer", "Central Instruction Source Code", "Compiled Instruction Set Computer"], "answer": "Complex Instruction Set Computer"},
        {"q": "What is Clock Speed measured in?", "options": ["Bytes", "Hertz (Hz)", "Ohms", "Watts"], "answer": "Hertz (Hz)"},
        {"q": "Which is a secondary storage device?", "options": ["RAM", "Cache", "SSD", "Register"], "answer": "SSD"}
    ],
    "python": [
        {"q": "What is the output of print(2 ** 3)?", "options": ["6", "8", "9", "5"], "answer": "8"},
        {"q": "Which keyword is used to define a function?", "options": ["func", "def", "define", "function"], "answer": "def"},
        {"q": "What data type is [1, 2, 3]?", "options": ["Tuple", "Set", "List", "Dictionary"], "answer": "List"},
        {"q": "How do you start a comment in Python?", "options": ["//", "/*", "#", "--"], "answer": "#"},
        {"q": "Which method adds an element to a list?", "options": ["push()", "add()", "append()", "insert()"], "answer": "append()"},
        {"q": "What is the output of 'Hello'[1]?", "options": ["H", "e", "l", "o"], "answer": "e"},
        {"q": "Is Python interpreted or compiled?", "options": ["Compiled", "Interpreted", "Both", "Neither"], "answer": "Interpreted"},
        {"q": "Which keyword is used for exception handling?", "options": ["catch", "except", "handle", "error"], "answer": "except"},
        {"q": "What does len() do?", "options": ["Returns length", "Returns type", "Returns last item", "Deletes item"], "answer": "Returns length"},
        {"q": "How do you import a module?", "options": ["include", "import", "using", "require"], "answer": "import"},
        {"q": "What is a Tuple?", "options": ["Mutable list", "Immutable list", "Dictionary key", "A class"], "answer": "Immutable list"},
        {"q": "Which operator is used for floor division?", "options": ["/", "//", "%", "**"], "answer": "//"},
        {"q": "What is PEP 8?", "options": ["Python style guide", "A library", "A database", "A framework"], "answer": "Python style guide"},
        {"q": "How to create a variable?", "options": ["var x = 5", "int x = 5", "x = 5", "declare x = 5"], "answer": "x = 5"},
        {"q": "What is __init__?", "options": ["A constructor", "A destructor", "A module", "A variable"], "answer": "A constructor"}
    ],
    "networks": [
        {"q": "What does HTTP stand for?", "options": ["Hyper Text Transfer Protocol", "High Transfer Text Protocol", "Hyper Text Transmission Protocol", "Hyper Test Transfer Protocol"], "answer": "Hyper Text Transfer Protocol"},
        {"q": "Which layer provides end-to-end communication?", "options": ["Physical", "Network", "Transport", "Session"], "answer": "Transport"},
        {"q": "What is the IPv4 address size?", "options": ["32 bits", "64 bits", "128 bits", "16 bits"], "answer": "32 bits"},
        {"q": "Which device connects different networks?", "options": ["Switch", "Hub", "Router", "Repeater"], "answer": "Router"},
        {"q": "What does DNS do?", "options": ["Encrypts data", "Resolves domain names to IP", "Assigns IP addresses", "Filters packets"], "answer": "Resolves domain names to IP"},
        {"q": "Which protocol is used for email?", "options": ["FTP", "SMTP", "HTTP", "SNMP"], "answer": "SMTP"},
        {"q": "What is a 'Packet'?", "options": ["A unit of data", "A hardware tool", "A software virus", "A network cable"], "answer": "A unit of data"},
        {"q": "OSI model has how many layers?", "options": ["4", "5", "6", "7"], "answer": "7"},
        {"q": "Which topology has a central node?", "options": ["Bus", "Ring", "Star", "Mesh"], "answer": "Star"},
        {"q": "What is a MAC address?", "options": ["Media Access Control", "Memory Access Code", "Main Access Computer", "Mail Access Center"], "answer": "Media Access Control"},
        {"q": "Which protocol is connectionless?", "options": ["TCP", "UDP", "FTP", "SSH"], "answer": "UDP"},
        {"q": "What is 'Ping' used for?", "options": ["Test reachability", "Download files", "Hack networks", "Send email"], "answer": "Test reachability"},
        {"q": "What is a Firewall?", "options": ["Stops fire", "Network security system", "A web browser", "An antivirus"], "answer": "Network security system"},
        {"q": "What does LAN stand for?", "options": ["Local Area Network", "Large Area Network", "Local Access Network", "Long Area Network"], "answer": "Local Area Network"},
        {"q": "Which port does HTTP use typically?", "options": ["21", "22", "80", "443"], "answer": "80"}
    ],
    "dbms": [
        {"q": "What does DBMS stand for?", "options": ["Data Base Management System", "Data Basic Manage System", "Digital Base Manage System", "Database Main System"], "answer": "Data Base Management System"},
        {"q": "What is a Primary Key?", "options": ["Any column", "Unique identifier for a record", "The first column", "A password"], "answer": "Unique identifier for a record"},
        {"q": "SQL stands for?", "options": ["Structured Query Language", "Simple Query Language", "Standard Question Language", "System Query Logic"], "answer": "Structured Query Language"},
        {"q": "Which command retrieves data?", "options": ["GET", "SELECT", "FETCH", "PULL"], "answer": "SELECT"},
        {"q": "What is a Foreign Key?", "options": ["A key from another country", "A link between two tables", "A backup key", "An encryption key"], "answer": "A link between two tables"},
        {"q": "Which is a DDL command?", "options": ["SELECT", "INSERT", "CREATE", "UPDATE"], "answer": "CREATE"},
        {"q": "What is Normalization?", "options": ["Organizing data to reduce redundancy", "Deleting data", "Backing up data", "Creating tables"], "answer": "Organizing data to reduce redundancy"},
        {"q": "What does ACID stand for?", "options": ["Atomicity, Consistency, Isolation, Durability", "Auto, Consistency, Internal, Data", "Atomicity, Class, Input, Data", "All, Common, Interval, Delete"], "answer": "Atomicity, Consistency, Isolation, Durability"},
        {"q": "Which is NOT a type of database?", "options": ["Relational", "NoSQL", "Hierarchical", "Spreadsheet"], "answer": "Spreadsheet"},
        {"q": "What is a 'View'?", "options": ["A virtual table", "A physical table", "A graph", "A screen"], "answer": "A virtual table"},
        {"q": "Which command removes a table?", "options": ["DELETE", "REMOVE", "DROP", "ERASE"], "answer": "DROP"},
        {"q": "What is a Cartesian Product?", "options": ["A Join of all rows", "A math formula", "A specific row", "An error"], "answer": "A Join of all rows"},
        {"q": "Which aggregate function counts rows?", "options": ["SUM()", "TOTAL()", "COUNT()", "ADD()"], "answer": "COUNT()"},
        {"q": "What is a Tuple in DBMS?", "options": ["A table", "A row", "A column", "A database"], "answer": "A row"},
        {"q": "Which operator is used for pattern matching?", "options": ["=", "MATCH", "LIKE", "SAME"], "answer": "LIKE"}
    ]
}